language: ruby

script: bundle exec rake travis

rvm:
  - 2.0.0
  - 2.1.0
  - ruby-head

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libpcap-dev -qq
  - gem update bundler

matrix:
  allow_failures:
    - rvm: 2.1.0
    - rvm: ruby-head
  fast_finish: true

env:
  global:
    - secure: K8XOn6irNlcpwwXsTJYH5jA7Iu3JM329kl8lzKIeku+5ypVTOBoknVr7NHQJEJvC/RWUmXh9IxPSo2xUVfO6gVum9rjCRzG+m7dVvhvM7I4E0nnCn/ouTkY+ksSBcPJ34UDb7Z4NzyrrG04MtJKLwbBtD61hRseeo3hOO9uAH6Y=
    - secure: lDefP7JDN2SBO/21Sm+TBIvXRYm6sTbyuJDaX76HXIX/ccf/oxYYuqfrxe32SgZuMXVHQcNKjl55kQMz0LtgSVLgKPhn2AaBn96j19F84FdcTV3wMJZURMGIrIgW7uKpc6KLGlQtAHnPcmKSm7/6Vhz2IbtlnZdEEC/jYagVOeY=
